modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L

keymap:
  - name: Fcitx5 SKK Trigger
    application:
      not: Alacritty
    remap:
      C-j: C-KEY_BACKSLASH
  - name: wofi
    application:
      only: wofi
    remap:
      C-n: down
      C-p: up
